# Site
repository: 
# favicon: images/favicon.ico

# Personal info
name: Matthew Reamer
title: Software Development Support Intern
email: mpreamer@mix.wvu.edu
website: www.github.com/mreamer24

# Social links
# twitter_username: facespics
github_username:  Mreamer24
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: matthew-reamer-69535a136
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/Profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Matt and I'm a Software Development Support Intern. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>C#</mark> and <mark>SQL</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Fishing
   - Video Game Modding
   - 
   - 

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
